import NavBar from "@/components/NavBar";
import NavSideBar from "@/components/NavSideBar";
import { ThemeProvider } from "@/components/ThemeProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import "highlight.js/styles/github-dark.css";
import type { Metadata } from "next";
import { roboto } from "../../public/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={`${roboto.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <NavSideBar />
            <div className="flex flex-col w-full items-center pb-30">
              <NavBar />
              <main className="flex flex-col w-full items-center justify-center max-w-[1280px]">
                {children}
              </main>
            </div>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
